### PR TITLE
JS Int8Array and ArrayBuffer interop

### PR DESCRIPTION
**Pull request by LolHens**
This PR adds a few interop methods for javascript's ArrayBuffer and Int8Array.
I haven't added any tests or doc yet because I first wanted to get some feedback on this.
Should something like this even be part of scodec or should this be a separate mini-library?

### CODE REVIEW

**Comment by mpilquist** [comment]
Looks good to me. I'm tempted to include these in `scodec.bits` package, without the `js` object, to avoid the need for an extra import. Thoughts?

**Comment by LolHens** [comment]
I could put them into the `ByteVectorPlatform` trait for the companion object and create another platform-dependent trait for the `class ByteVector`. Maybe calling it `ByteVectorInstancePlatform` or renaming `ByteVectorPlatform` to `ByteVectorObjPlatform`?

**Comment by mpilquist** [comment]
Yeah, in platform traits would be best IMO. I generally use `FooPlatform` and `FooCompanionPlatform` for the trait & companion object but if that would cause bincompat issues, then any naming scheme is fine here.

**Comment by LolHens** [comment]
I have made the requested changes. I had to create a second layer of platform specific traits where one is for scala versions and the other for platforms like js and jvm.

The 2.12.13 test found some potential binary incompatiblity because the private platform traits were renamed. Is that a false positive or is it a real issue in this case?

**Comment by mpilquist** [comment]
@LolHens Those look real to me, though not 100% certain.

**Comment by LolHens** [comment]
I have reverted the platform traits to their original name and its all green now.

**Pull request merged**
