### PR TITLE
scala-native support

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/scodec/scodec-bits/issues/69

### CODE REVIEW

**Comment by olafurpg** [comment]
Nice! Is there an expected release date? I'm in the process of porting fastparse to native and the module fastparseByte has a dependency on scodec-bits.

**Comment by mpilquist** [comment]
Running `test` from `coreNative` project fails b/c it tries to build `src/test/scala` directory. Seems like we need to disable test compilation completely in `coreNative` project.

**Comment by mpilquist** [comment]
Also, running `./nativeTest/target/scala-2.11/nativetest-out` results in a segmentation fault. Any ideas?

**Comment by olafurpg** [comment]
Hmmm. It should be possible to setup the build so `coreNative/test` works as expected, let me see what I can do about that.

> Also, running ./nativeTest/target/scala-2.11/nativetest-out results in a segmentation fault. Any ideas?

I'm unable to reproduce, 

```
$ time ./core/native/target/scala-2.11/scodec-bits-out
...
./core/native/target/scala-2.11/scodec-bits-out  0.01s user 0.00s system 43% cpu 0.025 total
```

What OS are you using? iirc, there were some problems with Arch Linux.

**Comment by mpilquist** [comment]
> Hmmm. It should be possible to setup the build so coreNative/test works as expected, let me see what I can do about that.

That would be great!

> What OS are you using?

OS X 10.12.5. I had to run `brew install bdw-gc` to get `coreNative` to build.

**Comment by olafurpg** [comment]
I opened https://github.com/scodec/scodec-bits/pull/75. coreNative/test runs in 2.11.11 and does nothing for other scalaVersion. With sbt-doge, it's possible to make the build configuration a bit simpler but I didn't want to add a build plugin.

I'm on OS X too, weird. I don't know enough about native to give pointers.

**Pull request merged**
